server:
  port: 8222
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer-service
          uri: lb:http://customer-service
          predicates:
            - Path=/api/v1/customer/**

        - id: product-service
          uri: lb:http://product-service
          predicates:
              - Path=/api/v1/product/**

        - id: payment-service
          uri: lb:http://payment-service
          predicates:
              - Path=/api/v1/payment/**

        - id: order-service
          uri: lb:http://order-service
          predicates:
              - Path=/api/v1/order/**
        - id: notification-service
          uri: lb:http://notification-service
          predicates:
            - Path=/api/v1/notification/**
#        - id: after_route
#          uri: ${server.hostname}:${server.port}/
#          predicates:
#          - After: 20225-06-50T17:42:47.789-07:00[America/Denver]
#          - Path=/red/
#          filters:
##            - CircuitBreaker=myCircuitBreaker
#            - name: CircuitBreaker
#              args:
#                name: myCircuitBreaker
#                fallbackUri: forward:/inCaseOfFailureUseThis
#                statusCodes:
#                  - 500
#                  - "NOT_FOUND"