eureka:
  instance:
    hostname: localhost
    instanceId: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  data:
    datasource:
      url: jdbc:postgresql://localhost:5432/jaggery
      username: postgres
      password: root
  jpa:
    hibernate:
      ddl-auto: update
    database--platform: org.hibernate.dialect.PostgreSQLDialect