server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql:http://localhost:5432/jaggery
    username: postgres
    password: root

jpa:
  hibernate:
    ddl-auto: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect