server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jaggery
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    customer-url: http://localhost:8222/api/v1/customer
    product-url: http://localhost:8222/api/v1/product
    notification-url: http://localhost:8222/api/v1/notification
    payment-url: http://localhost:8222/api/v1/payment
